services:
  postgres:
    image: postgres:14
    container_name: nest_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank-account
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: nest_app
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start:dev"
    env_file:
      - .env # Carrega as variáveis do arquivo .env
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
